-- Separate settlement tables: one for agents, one for companies.

CREATE TABLE IF NOT EXISTS `agent_settlements` (
  `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `agent_id` bigint(20) UNSIGNED NOT NULL,
  `amount` decimal(15,2) NOT NULL DEFAULT 0.00,
  `remark` text DEFAULT NULL,
  `settled_by` int(11) DEFAULT NULL COMMENT 'admin.admin_id',
  `last_settled_at` datetime DEFAULT NULL,
  `period_from` datetime DEFAULT NULL,
  `period_to` datetime DEFAULT NULL,
  `pay_in_commission` decimal(15,2) NOT NULL DEFAULT 0.00,
  `pay_out_commission` decimal(15,2) NOT NULL DEFAULT 0.00,
  `referral_commission` decimal(15,2) NOT NULL DEFAULT 0.00,
  `final_settlement_amount` decimal(15,2) NOT NULL DEFAULT 0.00,
  `settlement_status` enum('pending','settled','failed') NOT NULL DEFAULT 'pending',
  `previous_settlement_id` bigint(20) UNSIGNED DEFAULT NULL,
  `settlement_type` enum('FULL','PARTIAL','NET') NOT NULL DEFAULT 'NET',
  `commission_head` enum('ALL','PAYIN','PAYOUT','REFERRAL') NOT NULL DEFAULT 'ALL',
  `transaction_type` enum('DEBIT','CREDIT') NOT NULL DEFAULT 'DEBIT',
  `settlement_frequency` enum('manual','daily','weekly') NOT NULL DEFAULT 'manual',
  `previous_balance_snapshot` decimal(15,2) NOT NULL DEFAULT 0.00,
  `running_balance_snapshot` decimal(15,2) NOT NULL DEFAULT 0.00,
  `pay_in_volume` decimal(15,2) NOT NULL DEFAULT 0.00,
  `pay_out_volume` decimal(15,2) NOT NULL DEFAULT 0.00,
  `created_at` timestamp NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `idx_agent_settlements_agent` (`agent_id`),
  KEY `idx_agent_settlements_status` (`settlement_status`),
  KEY `idx_agent_settlements_period` (`period_from`, `period_to`),
  KEY `idx_agent_settlements_settled_at` (`last_settled_at`),
  CONSTRAINT `fk_agent_settlements_previous` FOREIGN KEY (`previous_settlement_id`) REFERENCES `agent_settlements` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `company_settlements` (
  `id` bigint(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `company_id` bigint(20) UNSIGNED NOT NULL,
  `amount` decimal(15,2) NOT NULL DEFAULT 0.00,
  `remark` text DEFAULT NULL,
  `settled_by` int(11) DEFAULT NULL COMMENT 'admin.admin_id',
  `last_settled_at` datetime DEFAULT NULL,
  `period_from` datetime DEFAULT NULL,
  `period_to` datetime DEFAULT NULL,
  `pay_in_commission` decimal(15,2) NOT NULL DEFAULT 0.00,
  `pay_out_commission` decimal(15,2) NOT NULL DEFAULT 0.00,
  `final_settlement_amount` decimal(15,2) NOT NULL DEFAULT 0.00,
  `settlement_status` enum('pending','settled','failed') NOT NULL DEFAULT 'pending',
  `previous_settlement_id` bigint(20) UNSIGNED DEFAULT NULL,
  `settlement_type` enum('FULL','PARTIAL','NET') NOT NULL DEFAULT 'NET',
  `commission_head` enum('ALL','PAYIN','PAYOUT') NOT NULL DEFAULT 'ALL',
  `transaction_type` enum('DEBIT','CREDIT') NOT NULL DEFAULT 'DEBIT',
  `settlement_frequency` enum('manual','daily','weekly') NOT NULL DEFAULT 'manual',
  `previous_balance_snapshot` decimal(15,2) NOT NULL DEFAULT 0.00,
  `running_balance_snapshot` decimal(15,2) NOT NULL DEFAULT 0.00,
  `pay_in_volume` decimal(15,2) NOT NULL DEFAULT 0.00,
  `pay_out_volume` decimal(15,2) NOT NULL DEFAULT 0.00,
  `created_at` timestamp NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `idx_company_settlements_company` (`company_id`),
  KEY `idx_company_settlements_status` (`settlement_status`),
  KEY `idx_company_settlements_period` (`period_from`, `period_to`),
  KEY `idx_company_settlements_settled_at` (`last_settled_at`),
  CONSTRAINT `fk_company_settlements_previous` FOREIGN KEY (`previous_settlement_id`) REFERENCES `company_settlements` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
